### ISSUE TITLE
[Swift] Assignment 1

### ISSUE THREAD

**Issue by harley** [harley/muvvy#1]
Hi, this is the submission /cc @coderschoolreview

Tab bar and search optional features aren't complete. I'll get to them! but the required and other optional features are there.

**Comment by chug2k** [comment]
You are the only one to come up with a creative application name. :dancer: 

I didn't mention this in class, but please be sure to follow the Swift code styling conventions for the homework. Here are a few useful guides:
- [Ray Wenderlich Swift Style Guide](https://github.com/raywenderlich/swift-style-guide)
- [Github Swift Style Guide](https://github.com/github/swift-style-guide)

Your code is pretty close to the style guide, so good job.

You are the only one who created a `Movie` model class. Good work!! :star2: The init method is much easier than passing around dictionary values, in my opinion. 
- Nice work with the custom Movie cell.
- Nice work loading the images asynchronously.
- Note that your images are stretched. You should observe the UIContentMode of the UIImageView. By default, it will stretch the image to match your dimensions, which is probably not what you want.
- Nice work implementing the error message on network failure. Next time consider using `UIView.animateWithDuration` to fade or slide the message instead of just `hide` and `show`. 
- You should also show "Network Error" for the Movie Details screen, when you try to load the high resolution image and there is no network...so listen to the Notification there. Good job on `NSNotification`, you're ahead of the game. 
- Search bar seems to work for me! Good job. Tab bar, not so much. 
- Some movies, like Furious 7, have a long synopsis that gets truncated on the details screen. Can you tell me how you would change your implementation to allow a user to read an entire synopsis? 

This is a great submission - very solid work. Hope to see even better this week.

**Comment by harley** [comment]
- Use Aspect Fit mode for UIImageView now
- Use UIView.animateWithDuration for the network error display. Added "x" to close it as well (changes committed)
- I would expand the synopsis label's area upon tap. I can still leave some space at the top for the user to exit out of the "detailed synopsis" view or i can make the synopsis full screen via a modal style and the user can exit to go back to enjoy the poster image)

thanks a lot! i didn't have time for the grid/list and the tab bar set up so as to reuse the MoviesView controller, but i'm sure I'll need to do that soon enough in another exercise.

**Comment by coderschoolreview** [comment]
:sweat: Sorry but the deadline for submissions has closed. We hope to see you in a future class - to be notified of when new classes open, be sure to like us on facebook at http://www.facebook.com/coderschoolvn.

**Comment by coderschoolreview** [comment]
test

**Comment by coderschoolreview** [comment]
another test (sorry for spamming)

**Comment by coderschoolreview** [comment]
test 3

**Comment by coderschoolreview** [comment]
test 4

**Comment by coderschoolreview** [comment]
test 4

**Comment by coderschoolreview** [comment]
test 5

**Comment by coderschoolreview** [comment]
test 6

**Comment by coderschoolreview** [comment]
test 7

**Comment by coderschoolreview** [comment]
test 8
